targets:
  $default:
    builders:
      json_api_generator|annotations:
        enabled: true

builders:
  json_api_generator:
    target: ":json_api_generator"
    import: "package:json_api_generator/generators.dart"
    builder_factories: ["generateJsonClass"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
