name: example
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  annotations:
    path: ../annotations/
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_riverpod: ^2.4.6
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_custom_generator:
    path: ../riverpod_custom_generator/
  widget_generator:
    path: ../widget_generator/
  riverpod_lint: ^2.0.1

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true
