name: example
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  annotations:
    path: ../annotations/


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  generators:
    path: ../generators/

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
