targets:
  $default:
    builders:
      laia_widget_generator|laia_annotations:
        enabled: true

builders:
  laia_widget_generator:
    target: ":laia_widget_generator"
    import: "package:laia_widget_generator/laia_widget_generator.dart"
    builder_factories: ["generateHomeWidgetElement", "generateElementWidget", "generateGenericWidgets", "generateHomeWidget", "generateListWidget"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
