targets:
  $default:
    builders:
      riverpod_generator|annotations:
        enabled: true

builders:
  riverpod_generator:
    target: ":riverpod_generator"
    import: "package:riverpod_generator/generators.dart"
    builder_factories: ["generateRiverpod"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
