// Run before flutter test: dart run test/support/generate_fixtures.dart
import 'dart:io';
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:laia_widget_generator/src/list_widget_generator.dart';
import 'package:laia_widget_generator/src/generic_widgets_generator.dart';
import 'package:laia_riverpod_custom_generator/src/riverpod_generator.dart';
import 'package:source_gen/source_gen.dart';

class UnusedBuildStep implements BuildStep {
  @override
  dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}

ConstantReader annotation(ClassElement model, String name) =>
    ConstantReader(model.metadata
        .firstWhere(
            (m) => m.computeConstantValue()?.type?.element?.name == name)
        .computeConstantValue());

Future<void> main() async {
  final resolved = await resolveFile2(
      path: File('test/support/models.dart').resolveSymbolicLinksSync());
  final library = (resolved as ResolvedUnitResult).libraryElement;
  final user = library.getClass('User')!;
  final step = UnusedBuildStep();
  final list = ListWidgetGenerator().generateForAnnotatedElement(
      user, annotation(user, 'ListWidgetGenAnnotation'), step);
  final plain = library.getClass('Plain')!;
  final plainList = ListWidgetGenerator().generateForAnnotatedElement(
      plain, annotation(plain, 'ListWidgetGenAnnotation'), step);
  final generic = library.getClass('GenericWidgets')!;
  final widgets = GenericWidgetsGenerator().generateForAnnotatedElement(
      generic, annotation(generic, 'GenericWidgetsGenAnnotation'), step);
  final providers = RiverpodCustomGenerator().generateForAnnotatedElement(
      user, annotation(user, 'RiverpodGenAnnotation'), step);
  for (final source in [list, plainList, widgets, providers]) {
    parseString(content: source, throwIfDiagnostics: true);
  }
  final directory = Directory('test/generated')..createSync(recursive: true);
  File('${directory.path}/list_source.txt').writeAsStringSync(list);
  File('${directory.path}/plain_source.txt').writeAsStringSync(plainList);
  final output = '''
// Generated by test/support/generate_fixtures.dart. Do not edit.
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:tuple/tuple.dart';
import 'package:http/http.dart' as api;
import '../support/models.dart';

const baseURL = 'https://example.invalid';
api.Client http = api.Client();
Future<Map<String, String>> getHeaders() async => {'Content-Type': 'application/json'};
class AppColors {
  static const indigo = Colors.indigo;
  static const surface = Colors.white;
  static const muted = Colors.grey;
}
class Styles {
  static const buttonPrimaryColor = Colors.indigo;
  static const buttonPrimaryColorHover = Colors.blue;
}
${list.substring(list.indexOf('class UserPaginationState'), list.indexOf('class _UserListRow')).replaceAll('_UserHeaderRow', 'TestUserHeaderRow')}
${widgets.substring(widgets.indexOf('class CustomPagination '), widgets.indexOf('class BoolWidget '))}
${providers.substring(providers.indexOf('class UserPaginationData'))}
''';
  File('${directory.path}/listing.dart').writeAsStringSync(output);
}
