targets:
  $default:
    builders:
      laia_riverpod_custom_generator|laia_annotations:
        enabled: true

builders:
  laia_riverpod_custom_generator:
    target: ":laia_riverpod_custom_generator"
    import: "package:laia_riverpod_custom_generator/laia_riverpod_custom_generator.dart"
    builder_factories: ["generateRiverpod"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
