name: laia_riverpod_custom_generator
description: It is a code generation package that generates the riverpod providers for the curd operations given dart class model. 

version: 0.0.11
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.1
  source_gen: ^1.5.0
  laia_annotations: ^0.0.7
  analyzer: ^5.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
